apiVersion: v1
kind: PersistentVolume
metadata:
  name: rhymix-web-html-pv
spec:
  storageClassName: web-app
  capacity:
    storage: 200Mi
  accessModes:
    - ReadOnlyMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: {{ .Values.global.nfsHost }}
    path: {{ .Values.global.nfsPath }}/app
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rhymix-web-files-pv
spec:
  storageClassName: web-files
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
    - rw
  nfs:
    server: {{ .Values.global.nfsHost }}
    path: {{ .Values.global.nfsPath }}/app/_rhymix/files
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rhymix-web-layout-pv
spec:
  storageClassName: web-layout
  capacity:
    storage: 50Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: {{ .Values.global.nfsHost }}
    path: {{ .Values.global.nfsPath }}/app/custom/layouts/ibs_layout
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rhymix-web-skin-pv
spec:
  storageClassName: web-skin
  capacity:
    storage: 10Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: {{ .Values.global.nfsHost }}
    path: {{ .Values.global.nfsPath }}/app/custom/modules/board/skins/faq
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rhymix-web-install-pv
spec:
  storageClassName: web-install
  capacity:
    storage: 5Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: {{ .Values.global.nfsHost }}
    path: {{ .Values.global.nfsPath }}/app/custom/modules/install/script
  persistentVolumeReclaimPolicy: Retain
